[package]
name = "design-pattern"
version = "0.1.0"
edition = "2021"

[[bin]]
name = 'singleton'
path = "./singleton/main.rs"

[[bin]]
name = 'factoryMethod'
path = "./factoryMethod/main.rs"

[dependencies]
lazy_static = "1.4.0"
once_cell = "1.19.0"