[package]
name = "rsrender"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"
wasm-react = "0.6.0"

[lib]
crate-type = ["cdylib", "rlib"]